INSERT INTO tbl_categories (FName,LName) VALUES ('Компʼютери та комплектуючі', '123');
INSERT INTO tbl_categories (FName,LName) VALUES ('Техніка для дому', '123');
INSERT INTO tbl_categories (FName,LName) VALUES ('Телефони, факси', '123');
INSERT INTO tbl_products (CategoryId, Name, Description, Price, CreatedDate) VALUES (3, 'Телефон Panasonic KX-TG1611UAR', 'Потужний телефони', 1330, GETDATE());
INSERT INTO tbl_products (CategoryId, Name, Description, Price, CreatedDate) VALUES (2, 'Фен Dyson Supersonic Nural Strawberry Bronze', 'Потужний фен', 24989, GETDATE());
INSERT INTO tbl_products (CategoryId, Name, Description, Price, CreatedDate) VALUES (1, 'Оперативна пам’ять Kingston FURY', 'Потужний апарат', 2307, GETDATE());
INSERT INTO tbl_products (CategoryId, Name, Description, Price, CreatedDate) VALUES (1, 'SSD-накопичувач Crucial T700', 'Потужний апарат', 11785, GETDATE());
INSERT INTO tbl_products (CategoryId, Name, Description, Price, CreatedDate) VALUES (1, 'Відеокарта MSI GeForce RTX 5080', 'Відаха', 88888, GETDATE());
INSERT INTO tbl_order_statuses (Name)  VALUES ('Новий заказ');
INSERT INTO tbl_order_statuses (Name)  VALUES ('Відмінено');
INSERT INTO tbl_order_statuses (Name)  VALUES ('Товар отримано');
INSERT INTO tbl_order_statuses (Name)  VALUES ('Комплектується');
INSERT INTO tbl_order_statuses (Name)  VALUES ('Очікує в магазині');
INSERT INTO tbl_users (FirstName, LastName, Email, PhoneNumber, Password) VALUES ('Іван', 'Петров', 'ivan@example.com', '+380501234567', 'hashed_password_1');  
INSERT INTO tbl_users (FirstName, LastName, Email, PhoneNumber, Password) VALUES ('Петро', 'Іванов', 'petro@example.com', '+380671234567', 'hashed_password_2');  
INSERT INTO tbl_users (FirstName, LastName, Email, PhoneNumber, Password) VALUES ('Семен', 'Сидоров', 'semen@example.com', '+380931234567', 'hashed_password_3');  
INSERT INTO tbl_users (FirstName, LastName, Email, PhoneNumber, Password) VALUES ('Юхим', 'Коваленко', 'yukhym@example.com', '+380991234567', 'hashed_password_4');  
INSERT INTO tbl_orders (UserId, OrderStatusId, CreatedDate) VALUES (1, 5, '2025-02-20 15:30:00');
INSERT INTO tbl_order_items (OrderId, ProductId, Count, CurrentPrice) VALUES (1, 5, 1, 88888.00);  
INSERT INTO tbl_order_items (OrderId, ProductId, Count, CurrentPrice) VALUES (1, 2, 2, 24989.00); 